Ongoing work -- adding a checkpoint

diff --git a/app/coverage/binvis/Makefile b/app/coverage/binvis/Makefile
--- a/app/coverage/binvis/Makefile
+++ b/app/coverage/binvis/Makefile
@@ -1,3 +1,9 @@
+# Design file parameter - can be overridden from command line (includes extension)
+# DESIGN_FILE ?= jukebox.v
+# Design name derived from design file (without extension)
+
+DESIGN_NAME = $(basename $(DESIGN_FILE))
+
 CFLAGS:=-m64 
 
 plat:= $(shell vcs -platform )
@@ -25,40 +31,51 @@ endif
 
 VISIT = visit.o
 
-all:
+
+e2e: check_design_file
+	make clean_results
+	make clean
+	make all DESIGN_FILE=$(DESIGN_FILE) && make run DESIGN_FILE=$(DESIGN_FILE) > a1.txt
+	make -f Makefile_cpp.mk clean && make -f Makefile_cpp.mk all DESIGN_FILE=$(DESIGN_FILE) > a2.txt
+	make clean
+
+check_design_file: $(DESIGN_FILE)
+	@test -n "$(DESIGN_FILE)" || (echo "Error: DESIGN_FILE is not set" && exit 1)
+
+all: check_design_file
 	rm -rf binvis visit.o urgReport ucli.key simv.daidir csrc simv sim.log simv.vdb binvis.log cm.log
-	vcs -sverilog -cm line jukebox.v
+	vcs -sverilog -cm line $(DESIGN_FILE)
 	./simv -cm line -l sim.log
 	g++ -g -I$(INC) -c visit.cc ${CFLAGS}
 	g++ -g -I$(INC) -o binvis binvis.cc $(VISIT)  -ldl -lm -lpthread  $(LIB) ${CFLAGS}
 	./binvis simv.vdb >& binvis.log
 	@echo Output is in file binvis.log
 
-all_cg:
+all_cg: check_design_file
 	rm -rf binvis visit.o urgReport ucli.key simv.daidir csrc simv sim.log simv.vdb binvis.log cm.log
-	vcs -sverilog jukebox.v -assert disable_cover -cm line 
+	vcs -sverilog $(DESIGN_FILE) -assert disable_cover -cm line 
 	./simv -cm line -l sim.log
 	g++ -g -I$(INC) -c visit.cc ${CFLAGS}
 	g++ -g -I$(INC) -o binvis binvis.cc $(VISIT)  -ldl -lm -lpthread  $(LIB) ${CFLAGS}
 	./binvis simv.vdb >& binvis.log
 	@echo Output is in file binvis.log
 
-
-
-binvis: binvis.cc $(VISIT)
+binvis: binvis.cc $(VISIT) check_design_file
 	g++ -g -I$(INC) -o binvis binvis.cc $(VISIT) -ldl -lm -lpthread  $(LIB) ${CFLAGS}
 
 $(VISIT) : visit.cc visit.hh
 	g++ -g -I$(INC) -c visit.cc ${CFLAGS}
 
-clean:
-	rm -rf binvis visit.o urgReport ucli.key simv.daidir csrc simv sim.log simv.vdb binvis.log cm.log sim2.log a1.txt a2.txt sim2.log
-
-test: jukebox.v binvis
-	vcs -sverilog -cm line jukebox.v
+test: binvis check_design_file
+	vcs -sverilog -cm line $(DESIGN_FILE)
 	./simv -cm line -l sim2.log 
 
-run: binvis test
+run: binvis test check_design_file
 	./binvis simv.vdb >& binvis.log
 	@echo Output is in file binvis.log
 
+clean_results:
+	rm -rf a1.txt a2.txt coverage_output.json
+
+clean:
+	rm -rf binvis_cpp binvis visit.o urgReport ucli.key simv.daidir csrc simv sim.log simv.vdb binvis.log cm.log sim2.log sim2.log binvis_cpp.log 
